Validate user name format
DARIAEngineering/dcaf_case_management pull request #2724
Opened 2022-10-18 21:56 UTC by djohnston32

I rule and have completed some work on Case Manager that's ready for review!

Add validation on "name" field for user model.

This pull request makes the following changes:
* Adds regex for validating name format
* Adds a test to ensure we're still allowing valid names with special characters like dashes and accent marks
* Adds a test for notable invalid cases: injecting a website name, accidentally supplying an email address in the name field

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

2022-10-22 17:01 UTC, colinxfleming requested changes
I should have pulled this for you earlier, but here's the characters that currently appear:

```
irb(main):014:0> names.join('').split('').uniq.sort.join('')
=> "\t '(),-.@ABCDEFGHIJKLMNOPQRSTUVWYZabcdefghijklmnopqrstuvwxyzáèëó
```

there's only one instance of @ and one instance of a name with a period in it, so I feel comfortable taking those out. There are a BUNCH of parens though so we'll probably want to allowlist those? No idea about the tabs though, ha.

So I think the two actions here are:
* add an error message to tell people how to fix scrub names
* loosen the req here a little bit to allow quotes, parens, and commas?

then I think this is good to go. thanks for this, it's great work.

2022-10-24 17:41 UTC, djohnston32 commented
Hmm, we may have a bit of a problem if there's a user with a period in their name. That one's really important to block since that's the only way to avoid e.g. "evil.com" without explicitly listing out domain patterns to block. But leaving the blanket validation against the period means that existing user won't be able to update their name or password. Best option might be to allow "untouched" name fields somehow so we can blanket allow names that already exist. Still causes problems if somebody named "firstname.lastname" decides to change to "newfirstname.newlastname" but maybe that's ok.

2022-10-24 18:02 UTC, djohnston32 commented
I just threw an `if: :name_changed?` on there and that seems to work.

2022-10-24 20:16 UTC, djohnston32 commented on test/controllers/users_controller_test.rb
> +      ['wikipedia.org', '*****', 'asdf@email.com'].each do |name|
No problem!

2022-10-24 20:20 UTC, djohnston32 commented
> So I think the two actions here are:
> 
>     * add an error message to tell people how to fix scrub names
> 
>     * loosen the req here a little bit to allow quotes, parens, and commas?

It's hard to tell but the quote-looking thing in the regex is a backtick not an apostrophe, so quotes, parens, and commas are all allowed with the current regex. I included a name with an apostrophe in the tests to be extra sure it's allowed since I figure that's something especially easy to get wrong.

2022-10-24 20:25 UTC, djohnston32 commented
Just realized since parens are allowed, I don't need the change removing parens in the admin user name. Will fix and updated.

2022-10-27 00:49 UTC, colinxfleming approved these changes
really great work here. thank you very much for thinking through this problem so thoroughly!

2022-10-27 00:49 UTC, colinxfleming commented on app/models/user.rb
> +            if: :name_changed?
`name_changed` is a great way of handling this. great call here

2022-10-27 00:49 UTC, merged