Practical support: add support_date field
DARIAEngineering/dcaf_case_management pull request #2893
Opened 2023-03-27 19:12 UTC by mercedesb

Complex abortions can be a multi-day process, and patients may need rides etc on multiple days. We should adjust our practical support flow to allow this case.

This pull request makes the following changes:
* Remove support type uniqueness constraint
* Add support_date to practical support model
* Update practical support UI to allow editing support_date

<img width="875" alt="image" src="https://user-images.githubusercontent.com/9774690/228042514-ea702ceb-b412-4b09-ba7f-814e8a624993.png">

It relates to the following issue #s: 
* Fixes #2882 

Open questions
* I didn't add any validations for support_date. I didn't think it made sense to require presence b/c there will be a whole bunch of existing records without a date. Let me know if you want any validation checking that the date is in the future or something like that.
* Let me know if you prefer something different for the UI changes.
* I'm not great at Spanish, I think my translation makes sense but probably good to have someone fluent make sure it's correct.

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

2023-03-28 00:45 UTC, colinxfleming reviewed
looking great on first glance! I think I would say let's move `Remove` and the new date field onto a second row and add some spacer indicator -- that's gonna get cramped on small screens. So I think something like:

* Row 1: Support Needed, providing Fund, Amount
* Row 2: Date, confirmed, Remove button
* some kinda line break/hr/spacer (I'm not sure we have a good existing example of this, so follow your heart)

other than that I think this is extremely looking good.

re: the other questions, 
* I don't think you need to add a validation for support date and we're generally in the habit of 'collect less data, not more, unless it's crucial' -- I don't think support date is generally crucial.
* Don't worry about the spanish translation; our funds understand we're in the business of 'close enough' when it comes to spanish mode (and tend to reach out if we pitch something that doesn't make any sense)

I'll give this a deeper review in a few days!

2023-03-28 21:46 UTC, mercedesb commented
Okee dokee, I went ahead and updated the UI. The first screenshot is on a normal screen (and it'll just grow as the screen gets bigger) and the second screenshot is on a bit smaller screen.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/9774690/228373434-60ab4bca-5d12-4a55-b94f-39ded4d6534f.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/9774690/228373489-148d596f-a5a9-4fe1-baaf-c218f072155f.png">

2023-04-08 20:31 UTC, colinxfleming requested changes
The design and flow of this is spot on! Marking requested changes because of the form deleting bug noted inline. I think this is probably a result of the button moving inside some form elements or something like that, such that the autocomplete of the form makes it think it wants to hit delete instead of patch. But not totally clear.

I think the system tests are correctly catching this bug, so I think when those are addressed we're good to go here.

Let me know if you've got any questions or need an assist here. Sorry for the late review!

2023-04-08 20:31 UTC, colinxfleming commented on app/views/practical_supports/_entries.html.erb
> +  <div class="row practical-support-headers">
I'm not quite sure what's happening here, but it looks like when I update an attribute on one of these entries it deletes it from db. To recreate, start with something like this:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/3866868/230741298-c00b3cfe-3df4-4d46-b439-fc841a8f38d3.png">

after unchecking the confirm box, it disappears (and deletes from db):

<img width="855" alt="image" src="https://user-images.githubusercontent.com/3866868/230741338-ce329ec0-dc70-405a-b815-4f43e640aa70.png">

2023-04-22 17:36 UTC, mercedesb commented
@colinxfleming sorry about the delay in getting this fixed. I started a new job 2 weeks ago and that's been taking up all my brain space. I think this should be good to go now. Pesky `<% end %>` in the wrong place.

2023-06-19 14:52 UTC, colinxfleming approved these changes
working great for me. sorry it took so long to review this! thank you very much!

2023-06-19 14:52 UTC, merged